name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x 
      - name: test secret envionment
        run: echo $TEST
        env:
          TEST: ${{ secrets.TEST }}
      - name: test secret envionment via node
        run: node -e "console.log(process.env)"
        env:
          TEST: ${{ secrets.TEST }}
